version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 20
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 120
      runas: root
