version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - echo "📦 installing packages..."
            - echo "✅ Packages installed successfully."
    build:
        commands:
            - echo "🚧 Starting compiling packages..."
            - echo "✅ Build passed successfully."
    post_build:
        commands:
            - echo "🚚 Performing post-build packing and operations..."
            - echo "✅ Post build successful"

artifacts:
  files:
    - '**/*'
  name: deploy-nodejs-build-artifacts
